# CONFIGURAÇÃO BÁSICA DO SPRING
spring.datasource.url=${STORAGE_SERVICE_LINK}
spring.datasource.username=${ACESS_USER_CONTROL}
spring.datasource.password=${ACESS_USER}

# CONFIGURAÇÃO PARA O ORACLE DATABASE
# CRIAR A TABELA DE CONTROLE DE MIGRAÇÃO NO BANCO DE DADOS
spring.flyway.baselineOnMigrate=true

# MOSTRAR AS INSTRUÇÕES SQL EXECUTADAS NO BANCO DE DADOS
spring.jpa.show-sql=true

# QUEBRAR A EXIBIÇÃO DA INSTRUÇÃO SQL EM VÁRIAS LINHAS
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect