CREATE SEQUENCE ALIMENTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE
    NO CYCLE;

CREATE TABLE TBL_ALIMENTOS(
    ALIMENTO_ID INTEGER DEFAULT  ALIMENTO_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    PORCAO VARCHAR(100) NOT NULL,
    QTDE_PROTEINAS NUMBER(9,3) NOT NULL
    QTDE_CARBOIDRATOS NUMBER(9,3) NOT NULL,
    QTDE_GORDURAS NUMBER(9,3) NOT NULL,
    QTDE_CALORIAS NUMBER(9,3) NOT NULL,
    TOTAL_CALORIAS NUMBER(9,3) NOT NULL
);